- name: configuring DB server
  hosts: db
  become: yes
  roles: # this will search for roles folder is present or not,if present then it will read folders,files sequentially and execute the module
  - db