- name: install nginx
  ansible.builtin.dnf:
    name: nginx
    state: latest

- name: start and enable nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes
  
- name: removing default content in html directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: creating html directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

- name: download and unzip frontend code
  ansible.builtin.unarchive:
    src: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
    dest: /usr/share/nginx/html
    remote_src: yes # it indicates that file is present in the remote server

# if there is a change in configuration , then you need to restart the nginx server

- name: copy backend conf
  ansible.builtin.template:
    src: expense.conf.j2
    dest: /etc/nginx/default.d/expense.conf
  notify: # instaed of ansible.builtin.service we are using handlers, at which you can restart the nginx server,after using handlers , we need to mention  them in this format
  - restart nginx

#/- name: restart nginx service
  #ansible.builtin.service:
    #name: nginx
    #state: restarted 