- name: deleting app directory
  ansible.builtin.file:
    path: /app
    state: absent
  #ignore_errors: yes

- name: create app directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: download and extracting backend code
  ansible.builtin.unarchive:
    src: "https://expense-builds.s3.us-east-1.amazonaws.com/expense-{{ component }}-v2.zip"
    dest: /app
    remote_src: yes

